[package]

name = "lodepng"
version = "0.0.1"
authors = ["Peter Atashian <retep998@gmail.com>"]
links = "lodepng"
build = "build.rs"

[dependencies.image]
git = "https://github.com/PistonDevelopers/image"

[build-dependencies]
gcc = "*"
